import { StyleSheet } from 'react-native';
import { colors, fonts, spacing, radius } from '@/constants/theme';
import { globalStyles } from '@/styles/global';

export const styles = StyleSheet.create({
  container: globalStyles.screen,
  tabContainer: {
    ...globalStyles.row,
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[4],
    gap: spacing[2],
  },
  tab: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  activeTab: {
    backgroundColor: colors.indigoPunch,
    borderColor: colors.indigoPunch,
  },
  activeTabText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 13,
    color: colors.white,
  },
  inactiveTabText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 13,
    color: colors.textSecondary,
  },
  scrollContent: {
    paddingBottom: 110,
  },
  mineHeader: {
    paddingHorizontal: spacing[5],
    marginBottom: spacing[4],
    gap: spacing[2],
  },
  scanButton: {
    ...globalStyles.row,
    justifyContent: 'center',
    backgroundColor: colors.indigoPunch,
    paddingVertical: 12,
    borderRadius: radius.md,
    gap: spacing[2],
    ...globalStyles.shadowMd,
    boxShadow: `0px 4px 8px ${colors.indigoPunch}1A`,
  },
  scanButtonText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 15,
    color: colors.white,
  },
  legendContainer: {
    marginTop: spacing[6],
    alignItems: "center",
    gap: spacing[4],
  },
  legendRow: {
    ...globalStyles.row,
    gap: spacing[4],
  },
  legendGradient: {
    flexDirection: "row",
    height: 12,
    width: 160,
    borderRadius: 6,
    overflow: "hidden",
    borderWidth: 0.5,
    borderColor: colors.borderDefault,
  },
  legendStep: {
    flex: 1,
  },
  legendText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 12,
    color: colors.textSecondary,
  },
  magicSlotInfo: {
    ...globalStyles.row,
    gap: spacing[2],
    backgroundColor: colors.peachBase,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.peachSoft,
    ...globalStyles.shadowSm,
    boxShadow: `0px 2px 4px ${colors.peachPunch}0D`,
  },
  magicSlotText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 12,
    color: colors.peachPunch,
  },
  bottomSheetPeek: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 90,
    backgroundColor: colors.white,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    alignItems: "center",
    paddingTop: 12,
    ...globalStyles.shadowMd,
    boxShadow: `0px 4px 16px ${colors.black}1A`,
    zIndex: 10,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  detailSheet: {
    height: 320,
    alignItems: 'stretch',
    paddingHorizontal: spacing[5],
  },
  dragHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.borderDefault,
    marginBottom: 16,
    alignSelf: 'center',
  },
  peekContent: {
    ...globalStyles.row,
    gap: spacing[2],
  },
  peekText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 14,
    color: colors.textPrimary,
  },
  detailHeader: {
    marginBottom: spacing[3],
  },
  detailTitleRow: {
    ...globalStyles.rowBetween,
    marginBottom: 4,
  },
  detailTitle: {
    fontFamily: fonts.display,
    fontSize: 20,
    color: colors.textPrimary,
  },
  detailSubtitle: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.textSecondary,
  },
  nudgeBanner: {
    ...globalStyles.row,
    backgroundColor: colors.peachBase,
    padding: 10,
    borderRadius: radius.md,
    gap: 8,
    marginBottom: spacing[4],
    borderWidth: 0.5,
    borderColor: colors.peachSoft,
  },
  nudgeText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 13,
    color: colors.peachPunch,
    flex: 1,
  },
  voteButton: {
    marginTop: spacing[6],
    height: 56,
  },
  memberSection: {
    gap: spacing[2],
  },
  sectionLabel: {
    fontFamily: fonts.bodySemibold,
    fontSize: 11,
    color: colors.textTertiary,
    letterSpacing: 1,
  },
  memberList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
  },
  memberChip: {
    ...globalStyles.row,
    backgroundColor: colors.indigoBase,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radius.full,
    gap: spacing[1],
  },
  memberChipText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 12,
    color: colors.indigoPunch,
  },
  busyChip: {
    backgroundColor: colors.pageBg,
  },
  busyChipText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 12,
    color: colors.textSecondary,
  },
  editNotice: {
    ...globalStyles.row,
    gap: spacing[2],
    padding: spacing[3],
    backgroundColor: colors.indigoBase,
    borderRadius: radius.md,
    borderWidth: 0.5,
    borderColor: colors.indigoSoft,
  },
  editNoticeText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 13,
    color: colors.indigoPunch,
  },
  legendBox: {
    width: 12,
    height: 12,
    borderRadius: 2,
    borderWidth: 0.5,
    borderColor: colors.borderDefault,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    ...globalStyles.center,
    padding: spacing[5],
  },
  modalContent: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing[6],
    gap: spacing[6],
  },
  modalHeaderRow: {
    ...globalStyles.rowBetween,
  },
  quickAddTitle: {
    fontFamily: fonts.display,
    fontSize: 22,
    color: colors.textPrimary,
  },
  formGroup: {
    gap: spacing[2],
  },
  formLabel: {
    fontFamily: fonts.bodySemibold,
    fontSize: 14,
    color: colors.textSecondary,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radius.md,
    padding: spacing[4],
    fontFamily: fonts.body,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.pageBg,
  },
  durationRow: {
    flexDirection: 'row',
    gap: spacing[2],
  },
  durationPill: {
    flex: 1,
    height: 44,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    ...globalStyles.center,
    backgroundColor: colors.pageBg,
  },
  activeDurationPill: {
    borderColor: colors.indigoPunch,
    backgroundColor: colors.indigoBase,
  },
  durationText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 14,
    color: colors.textSecondary,
  },
  activeDurationText: {
    color: colors.indigoPunch,
  },
  saveButton: {
    height: 54,
  },
  confirmModalContainer: {
    flex: 1,
    backgroundColor: colors.pageBg,
  },
  modalHeaderFixed: {
    padding: spacing[5],
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderDefault,
  },
  confirmModalTitle: {
    fontFamily: fonts.display,
    fontSize: 24,
    color: colors.textPrimary,
    marginBottom: 4,
  },
  confirmModalSubtitle: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  modalGridScroll: {
    paddingVertical: spacing[4],
  },
  confirmModalFooter: {
    flexDirection: 'row',
    padding: spacing[5],
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.borderDefault,
    gap: spacing[3],
  },
  discardButton: {
    flex: 1,
    height: 54,
    borderRadius: radius.md,
    backgroundColor: colors.pageBg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    ...globalStyles.center,
  },
  discardButtonText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 16,
    color: colors.textSecondary,
  },
  confirmButton: {
    flex: 2,
    height: 54,
    borderRadius: radius.md,
    backgroundColor: colors.indigoPunch,
    ...globalStyles.center,
    ...globalStyles.shadowMd,
    boxShadow: `0px 4px 8px ${colors.indigoPunch}1A`,
  },
  confirmButtonText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 16,
    color: colors.white,
  },
  modalHeaderTop: {
    ...globalStyles.rowBetween,
    marginBottom: 8,
  },
  previewToggle: {
    ...globalStyles.row,
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: colors.indigoBase,
    borderRadius: radius.full,
  },
  previewToggleText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 12,
    color: colors.indigoPunch,
  },
  imageAnchorContainer: {
    height: 200,
    backgroundColor: colors.black,
    position: 'relative',
  },
  anchorImage: {
    width: '100%',
    height: '100%',
    opacity: 0.8,
  },
  imageOverlayLabel: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  imageOverlayText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 10,
    color: colors.white,
    letterSpacing: 1,
  },
  impactBanner: {
    ...globalStyles.row,
    backgroundColor: colors.peachBase,
    padding: 12,
    borderRadius: radius.md,
    gap: 10,
    marginBottom: spacing[3],
    borderWidth: 1,
    borderColor: colors.peachSoft,
  },
  impactText: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.peachDeep,
    flex: 1,
    lineHeight: 18,
  },
  warningBanner: {
    ...globalStyles.row,
    backgroundColor: '#FFF1F1',
    padding: 12,
    borderRadius: radius.md,
    gap: 10,
    marginBottom: spacing[3],
    borderWidth: 1,
    borderColor: colors.peachSoft,
  },
  warningText: {
    fontFamily: fonts.bodySemibold,
    fontSize: 13,
    color: colors.peachDeep,
    flex: 1,
  },
  bold: {
    fontFamily: fonts.bodySemibold,
    color: colors.peachPunch,
  },
  uncertaintyHint: {
    ...globalStyles.row,
    gap: 8,
    marginTop: 4,
  },
  uncertaintyDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.peachMid,
  },
  uncertaintyText: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
});
